Repository nahkim/ClassCard, pull requests merged in 2022-12, with the labels that each got.

#17 FIX: card의 views.py에서 if문 안 먹히는거 해결
  card/templates/card/detail.html
  card/views.py
  static/css/detail.css
  static/css/styles.css
  templates/base.html
Labels: FIX

#18 FEAT:add detail
  card/templates/card/detail.html
  static/css/detail.css
  static/images/bg_1.jpg
  static/images/bg_2.jpg
  static/images/bg_3.jpg
  static/images/bg_4.jpg
  static/images/bg_5.jpg
Labels: STYLE

#19 FEAT : 주요 혜택에 폰트 아이콘 넣기
  card/templates/card/detail.html
  card/views.py
  static/css/detail.css
Labels: FEAT

#20 FEAT: detail
  card/templates/card/detail.html
  templates/base.html
Labels: STYLE

#21 FEAT : search 혜택 필터링
  card/templates/card/search.html
  card/urls.py
  card/views.py
Labels: FEAT

#22 FIX : views.detail 수정 완료
  card/views.py
Labels: FIX

#23 FIX: 카드 이미지 방향 설정 / 배너 중간에 카드 넣기 성공
  card/templates/card/detail.html
  card/views.py
  static/css/detail.css
  templates/base.html
Labels: FIX, STYLE

#24 FIX / STYLE: detail 페이지 카드 애니메이션에 기능 추가 / detail 페이지 주요 혜택에 새로운 카테고리 추가 / 아이콘도 추가
  card/templates/card/detail.html
  card/views.py
  static/css/detail.css
Labels: FIX, STYLE

#25 FEAT: 메인화면 수정
  static/css/styles.css
  static/js/test.js
  templates/base.html
  templates/main.html
Labels: FEAT, DOCS, STYLE

#26 STYLE: 디테일 페이지 디자인 수정
  card/templates/card/detail.html
  static/css/detail.css
Labels: STYLE

#27 FEAT: search다중필터링 구현 완료
  card/templates/card/search.html
  card/views.py
Labels: FEAT

#28 STYLE: 디테일 페이지 혜택 넣기
  card/migrations/0001_initial.py
  card/models.py
  card/templates/card/detail.html
  card/views.py
  card_data.csv
  config/views.py
  static/css/detail.css
Labels: STYLE

#29 FIX / FEAT : Search 페이지 버튼 누르면 색깔 변하기 기능 구현 / 댓글 쓰는 기능
  card/forms.py
  card/migrations/0002_detailcomment.py
  card/migrations/0003_detailcomment_rate.py
  card/migrations/0004_rename_post_detailcomment_card.py
  card/migrations/0005_detailcomment_created_at.py
  card/migrations/0006_auto_20221204_1525.py
  card/migrations/0007_detailcomment_updated_at.py
  card/models.py
  card/templates/card/detail.html
  card/templates/card/search.html
  card/urls.py
  card/views.py
  config/settings.py
  magazine/models.py
  requirements.txt
  static/css/detail.css
Labels: FEAT, FIX

#30 FEAT : 소셜 로그인 DB 연동
  accounts/admin.py
  accounts/forms.py
  accounts/migrations/0001_initial.py
  accounts/models.py
  accounts/templates/accounts/login.html
  accounts/templates/accounts/profile.html
  accounts/templates/accounts/signup.html
  accounts/views.py
  config/settings.py
  config/urls.py
Labels: FEAT

#31 Rothy
  accounts/admin.py
  accounts/forms.py
  accounts/models.py
  card/migrations/0001_initial.py
  card/migrations/0002_detailcomment.py
  card/migrations/0003_detailcomment_rate.py
  card/migrations/0004_rename_post_detailcomment_card.py
  card/migrations/0005_detailcomment_created_at.py
  card/migrations/0006_auto_20221204_1525.py
  card/migrations/0007_detailcomment_updated_at.py
  config/settings.py
Labels: FEAT

#32 STYLE: 디테일 페이지 수정
  accounts/migrations/0001_initial.py
  card/migrations/0002_alter_card_card_in_out.py
  card/migrations/0008_merge_20221205_1140.py
  card/migrations/0009_auto_20221205_1141.py
  card/templates/card/detail.html
  static/css/detail.css
Labels: STYLE

#35 FEAT: 디테일 페이지 후기 작성/ 삭제 비동기
  accounts/migrations/0002_alter_user_role.py
  card/migrations/0001_initial.py
  card/templates/card/detail.html
  card/urls.py
  card/views.py
  static/css/detail.css
Labels: FEAT, STYLE

#36 FEAT : 회원 관리 정보 추가
  accounts/forms.py
  accounts/migrations/0002_alter_user_role.py
  accounts/templates/accounts/login.html
  accounts/templates/accounts/signup.html
  accounts/templates/accounts/update.html
  accounts/urls.py
  accounts/views.py
  articles/models.py
Labels: FEAT

#37 FEAT : 2022 BEST CARD
  static/css/styles.css
  static/js/test.js
  templates/base.html
  templates/main.html
Labels: FEAT

#38 DOCS:signup.html
  accounts/migrations/0002_alter_user_role.py
  magazine/migrations/0002_auto_20221205_1622.py
  magazine/migrations/0002_rename_magezine_magazine.py
  magazine/migrations/0003_comment.py
  magazine/migrations/0004_alter_comment_parent_comment.py
  magazine/migrations/0005_auto_20221130_1720.py
  static/css/signup.css
  static/images/bg-img.png
  templates/allauth/account/base.html
  templates/allauth/account/signup.html
Labels: DOCS

#39 FEAT : 메인화면 전체
  templates/base.html
  templates/main.html
Labels: FEAT

#40 FEAT : SEARCH 페이지네이션 완성
  card/templates/card/search.html
  card/views.py
Labels: FEAT

#41 FEAT: Detail 페이지 후기 비동기 완료
  card/migrations/0002_alter_card_card_in_out.py
  card/migrations/0002_detailcomment.py
  card/migrations/0003_detailcomment_rate.py
  card/migrations/0004_rename_post_detailcomment_card.py
  card/migrations/0005_detailcomment_created_at.py
  card/migrations/0006_auto_20221204_1525.py
  card/migrations/0007_detailcomment_updated_at.py
  card/templates/card/detail.html
  card/views.py
  soso/__init__.py
  soso/admin.py
  soso/apps.py
  soso/migrations/__init__.py
  soso/models.py
  soso/templates/soso/login.html
  soso/tests.py
  soso/urls.py
  soso/views.py
  static/css/detail.css
  static/images/header_search copy.svg
Labels: FEAT

#42 FIX: NAV 수정
  templates/base.html
Labels: FIX, DOCS

#43 FEAT: 카드 맞춤 검색
  card/templates/card/search.html
Labels: FEAT

#45 fix : 매거진 비동기 실패 card -> migration 파일 이상발견, merge 후 숫자 붙은파일 지우고 풀땡겨주세요
  card/migrations/0001_initial.py
  card/migrations/0002_alter_card_card_in_out.py
  card/migrations/0002_detailcomment.py
  card/migrations/0003_detailcomment_rate.py
  card/migrations/0004_rename_post_detailcomment_card.py
  card/migrations/0005_detailcomment_created_at.py
  card/migrations/0006_auto_20221204_1525.py
  card/migrations/0007_detailcomment_updated_at.py
  card/templates/card/detail.html
  magazine/templates/magazine/detail.html
  soso/__init__.py
  soso/admin.py
  soso/apps.py
  soso/migrations/__init__.py
  soso/models.py
  soso/templates/soso/login.html
  soso/tests.py
  soso/urls.py
  soso/views.py
  templates/base.html
Labels: bug

#46 FIX:signup
  static/css/signup.css
  templates/allauth/account/messages/logged_in.txt
  templates/allauth/account/messages/logged_out.txt
  templates/allauth/account/signup.html
Labels: bug

#47 FIX: 메인화면 실험중
  static/css/styles.css
  static/js/test.js
  templates/base.html
  templates/main.html
Labels: FIX

#48 DOCS:login
  static/css/signup.css
  static/images/exclamation.png
  static/images/google_logo.png
  static/images/naver_logo.png
  templates/allauth/account/base.html
  templates/allauth/account/login.html
  templates/allauth/account/signup.html
Labels: DOCS

#50 FIX: 메인 화면 VISUAL
  static/css/styles.css
  static/images/class-card-img16.png
  static/images/visual1.png
  templates/main.html
Labels: FIX

#51 FIX: 메인화면 BEST3, MOST SEARCH
  static/css/styles.css
  static/js/test.js
  templates/base.html
  templates/main.html
Labels: FEAT, FIX

#56 FEAT: 에디터가 추천해주는 카드
  static/css/bootstrap.min.css
  static/css/styles.css
  static/js/test.js
  templates/base.html
  templates/main.html
Labels: FEAT, STYLE

#57 FEAT: 모두를 위해 만들다.PNG
  static/css/styles.css
  templates/main.html
Labels: FEAT, FIX, STYLE, REFACTOR

#58 FIX: magazine모델 이상 발견 모델&태그 필드 추가(기타)
  accounts/migrations/0003_auto_20221207_1148.py
  magazine/migrations/0004_alter_magazine_tag.py
  magazine/migrations/0005_alter_magazine_tag.py
  magazine/models.py
Labels: FIX

#59 FIX: 매거진 썸네일 이미지 추가
  magazine/forms.py
Labels: FIX

#61 FIX: CDN 수정
  static/js/profile.js
  templates/base.html
Labels: FEAT, FIX

#62 FEAT: 프로필 페이지
  accounts/templates/accounts/profile.html
  static/css/styles.css
Labels: FEAT

#63 FEAT: 고객센터 build & navbar 링크연결
  articles/templates/articles/eventhome.html
  card/templates/card/cardcompany.html
  card/urls.py
  card/views.py
  config/settings.py
  config/urls.py
  magazine/migrations/0006_alter_magazine_tag.py
  servicecenter/__init__.py
  servicecenter/admin.py
  servicecenter/apps.py
  servicecenter/forms.py
  servicecenter/migrations/0001_initial.py
  servicecenter/migrations/__init__.py
  servicecenter/models.py
  servicecenter/templates/servicecenter/create.html
  servicecenter/templates/servicecenter/detail.html
  servicecenter/templates/servicecenter/index.html
  servicecenter/tests.py
  servicecenter/urls.py
  servicecenter/views.py
  templates/base.html
Labels: FEAT

#64 DOCS:magazine
  magazine/templates/magazine/create.html
  magazine/templates/magazine/index.html
  static/css/magazine.css
Labels: DOCS

#65 FEAT:카드사 페이지
  card/templates/card/cardcompany.html
  card/templates/card/cardcompanylist.html
  card/urls.py
  card/views.py
  templates/base.html
Labels: FEAT

#66 FEAT: 필터 검색
  card/templates/card/search.html
  card/views.py
  config/views.py
  static/css/search.css
Labels: FEAT, FIX

#67 DOCS:base
  magazine/templates/magazine/detail.html
  templates/base.html
Labels: DOCS

#68 FIX: TEST
  static/css/styles.css
  templates/base.html
  templates/main.html
Labels: FIX

#70 FIX: 메인화면 VISUAL 수정
  static/css/styles.css
  static/images/class-card04.png
  static/images/class-img01.png
  static/images/class-img02.png
  static/images/class-img03.png
  templates/base.html
  templates/main.html
Labels: FEAT, FIX, DOCS

#71 FIX : 매거진 grade 범위 제한, nav_search에 매거진 추가
  config/views.py
  magazine/forms.py
  magazine/templates/magazine/detail.html
  templates/nav_search.html
Labels: FIX

#73 Ready
  templates/main.html
Labels: FEAT, FIX

#74 DOCS:magazine/detail
  magazine/templates/magazine/detail.html
  static/css/magazine.css
  static/images/profile.png
Labels: DOCS

#75 FEAT: SHARE TOOLBOX 기능
  templates/base.html
Labels: FEAT

#77 STLYE : 맞춤 카드 검색창 디자인
  card/templates/card/search.html
  card/views.py
  static/css/search.css
Labels: STYLE

#78 FEAT: MAIN
  card/views.py
Labels: FEAT

#80 FEAT: 카드 목록 페이지
  card/urls.py
  card/views.py
Labels: FEAT

#81 DOCS:magazine
  magazine/templates/magazine/index.html
  static/css/magazine.css
Labels: DOCS

#82 FIX: 카드사 수정
  card/migrations/0003_comparecard.py
  card/models.py
  card/templates/card/cardcompanylist.html
  card/templates/card/detail.html
  card/views.py
  magazine/migrations/0008_alter_magazine_tag.py
Labels: FIX

#83 Ready
  articles/templates/articles/eventhome.html
  static/css/styles.css
  static/js/test.js
  templates/base.html
  templates/main.html
Labels: FEAT, FIX, STYLE

#86 FEAT: 카드 검색_ 카드 목록페이지
  card/templates/card/card_list.html
Labels: FEAT, DOCS

#88 DOCS:cardlist
  card/templates/card/cardcompanylist.html
  magazine/migrations/0008_alter_magazine_tag.py
  static/css/card.css
  static/images/부산_logo.jpg
  static/images/부산_logo.png
Labels: DOCS

#89 FIX:magazine
  magazine/templates/magazine/index.html
Labels: DOCS

#90 Ready
  articles/templates/articles/eventhome.html
Labels: FEAT, FIX

#92 DOCS:service
  servicecenter/templates/servicecenter/index.html
  servicecenter/views.py
Labels: DOCS

#93 FIX : 메인 화면 회원 가입 링크 연결
  templates/base.html
Labels: FEAT, STYLE

#95 Ready
  accounts/templates/accounts/profile.html
  articles/templates/articles/eventhome.html
  magazine/migrations/0009_alter_magazine_tag.py
  templates/base.html
Labels: FEAT, FIX, DOCS, STYLE

#96 DOCS:service/detail
  servicecenter/templates/servicecenter/detail.html
Labels: DOCS

#97 FIX : profile 정보수정 -> 폼 삽입
  accounts/templates/accounts/update.html
Labels: FIX

#99 Ready
  accounts/templates/accounts/profile.html
Labels: FEAT, FIX

#100 DOCS:password/change
  templates/allauth/account/password_change.html
Labels: DOCS

#102 FIX : 메인페이지 join 버튼 변경
  templates/base.html
Labels: FEAT

#103 FEAT: 카드 비교 페이지
  accounts/templates/accounts/card_compare.html
  accounts/templates/accounts/profile.html
Labels: FEAT, FIX, STYLE

#104 FEAT : 2022top카드 리스트, most_search_list
  accounts/templates/accounts/profile.html
  accounts/views.py
  card/templates/card/rank.html
  card/templates/card/search_list.html
  card/urls.py
  card/views.py
  magazine/templates/magazine/detail.html
  magazine/templates/magazine/index.html
  magazine/urls.py
  magazine/views.py
  templates/main.html
Labels: FEAT

#105 DOCS:passwordchange
  templates/allauth/account/password_change.html
Labels: DOCS

#108 Ready
  accounts/templates/accounts/check_delete.html
  accounts/templates/accounts/profile.html
  articles/templates/articles/eventhome.html
  static/css/styles.css
  templates/main.html
Labels: FEAT, FIX

#109 FEAT : 회원가입시 이메일 인증 기능 추가
  config/settings.py
  config/views.py
Labels: FEAT

#110 Hagrid
  templates/allauth/account/password_change.html
Labels: DOCS

#111 FEAT: 이메일 인증 페이지 완료
  templates/allauth/account/verification_sent.html
Labels: FEAT

#112 DOCS:passwordreset/snippets/already_logged_in
  templates/allauth/account/password_reset.html
  templates/allauth/account/snippets/already_logged_in.html
Labels: DOCS

#115 DOCS:password_reset_from_key
  magazine/templates/magazine/index.html
  static/css/magazine.css
  templates/allauth/account/password_reset_from_key.html
Labels: DOCS

#116 FEAT: 비밀번호 초기화 페이지 완료
  templates/allauth/account/password_reset_done.html
Labels: FEAT

#118 FEAT: RANK 페이지 기본 틀 완성
  accounts/templates/accounts/profile.html
  card/templates/card/rank.html
  static/css/styles.css
  static/js/test.js
  templates/base.html
  templates/nav_search.html
Labels: FEAT

#119 FEAT: NAV_SEARCH 레이아웃 완료
  templates/nav_search.html
Labels: FEAT

#120 FIX : cardcompany.html 페이지네이션, nav_search.html 페이지네이션
  card/templates/card/cardcompany.html
  templates/nav_search.html
Labels: FIX

#121 FIX : nav-text search
  accounts/templates/accounts/profile.html
  accounts/views.py
  card/views.py
  magazine/views.py
  templates/base.html
  templates/nav_search.html
Labels: FIX

#122 DOCS:cardcompany
  card/templates/card/cardcompany.html
  static/css/card.css
Labels: DOCS

#123 DOCS:magazine
  magazine/templates/magazine/index.html
Labels: DOCS

#124 FEAT : 베스트 카드 페이지 기능 추가 및 수정
  card/templates/card/rank copy.html
  card/templates/card/rank.html
  card/views.py
  config/settings.py
Labels: FEAT

#125 DOCS:cardcompany
  card/templates/card/cardcompanylist.html
Labels: DOCS

#129 FIX: 카드사 배경화면 변경
  card/templates/card/cardcompanylist.html
Labels: FEAT, FIX, STYLE

#130 FEAT: 카드 맞춤 페이지
  card/templates/card/card_compare.html
  card/templates/card/card_list.html
  card/templates/card/detail.html
  card/templates/card/search.html
  card/urls.py
  card/views.py
  static/css/card_list.css
  static/css/styles.css
  templates/base.html
Labels: FEAT

#131 Ready
  card/templates/card/search_list.html
  static/css/search_list.css
  static/css/styles.css
  static/images/class_card_logo_1.png
  static/images/class_card_logo_2.png
  templates/base.html
  templates/main.html
Labels: FEAT

#133 DOCS:accounts/update
  accounts/templates/accounts/update.html
Labels: DOCS

#134 Ready
  card/templates/card/search_list.html
Labels: FEAT

#135 FEAT : 배포(requirements update, env 변경)
  .ebextensions/django.config
  .github/workflows/deploy.yml
  .project
  config/settings.py
  magazine/migrations/0001_initial.py
  magazine/migrations/0002_auto_20221205_1622.py
  magazine/migrations/0003_magazine_tag.py
  magazine/migrations/0004_alter_magazine_tag.py
  magazine/migrations/0005_alter_magazine_tag.py
  magazine/migrations/0006_alter_magazine_tag.py
  magazine/migrations/0007_alter_magazine_tag.py
  magazine/migrations/0008_auto_20221209_0938.py
  requirements.txt
Labels: FEAT

#136 FIX : allowhost
  config/settings.py
Labels: FIX

#137 DOCS:event
  articles/templates/articles/eventhome.html
Labels: DOCS

#138 Rothy
  accounts/templates/accounts/profile.html
  magazine/templates/magazine/detail.html
  magazine/views.py
  templates/allauth/account/login.html
Labels: FEAT

#140 DOCS:cardcompanylist
  card/templates/card/cardcompanylist.html
Labels: DOCS

#141 DOCS:favicon
  static/images/favicon.ico
  templates/base.html
Labels: DOCS

#142 STYLE : 카드 비교 페이지 끝
  card/templates/card/card_compare.html
  static/css/card_compare.css
Labels: STYLE

#143 FEAT: 페이지 레이아웃 구조
  card/templates/card/rank.html
Labels: FEAT

#144 DOCS:service/index
  servicecenter/templates/servicecenter/index.html
  static/css/service.css
Labels: DOCS

#145 fix: baeppopo
  .dbeaver/.credentials-config.json.bak
  .dbeaver/.data-sources.json.bak
  .dbeaver/.project-metadata.json.bak
  .dbeaver/credentials-config.json
  .dbeaver/data-sources.json
  .dbeaver/project-metadata.json
  .dbeaver/project-settings.json
  .project
  magazine/migrations/0002_alter_magazine_tag.py
Labels: FIX

#146 FIX: 사진 MARGIN 수정
  card/templates/card/rank.html
  card/templates/card/search_list.html
Labels: FEAT, FIX

#147 DOCS:base
  templates/base.html
Labels: DOCS

#148 Ready
  card/templates/card/rank.html
  card/templates/card/search_list.html
Labels: FIX, DOCS

#149 FEAT: RANK 페이지 기본 레이아웃 구조 완성
  card/templates/card/rank.html
Labels: FEAT, DOCS, STYLE

#152 FIX : 배포3
  config/settings.py
Labels: FIX

#153 Ready
  templates/base.html
  templates/main.html
Labels: FEAT, FIX

#154 fix : 배포 테스트 브랜치 분리
  .github/workflows/deploy.yml
Labels: FIX

#157 Ready
  card/templates/card/rank.html
  card/templates/card/search_list.html
  static/css/styles.css
  static/images/card_ad.PNG
  static/js/test.js
  templates/base.html
  templates/nav_search.html
Labels: FEAT, FIX

#158 Toto
  card/templates/card/rank.html
  requirements.txt
  templates/base.html
Labels: FIX

#159 DOCS:service/index
  servicecenter/templates/servicecenter/index.html
  servicecenter/views.py
Labels: DOCS

#160 DOCS:service/index
  servicecenter/templates/servicecenter/index.html
Labels: DOCS

#161 fix:rank.html
  card/templates/card/rank.html
Labels: FIX

#163 DOCS:magazine
  magazine/templates/magazine/index.html
Labels: DOCS

#168 Toto
  accounts/templates/accounts/profile.html
  card/templates/card/rank copy.html
  card/templates/card/rank.html
  card/templates/card/search_list.html
  card/views.py
  config/urls.py
  config/views.py
  magazine/templates/magazine/detail.html
  magazine/views.py
  static/css/default.css
  static/css/main.css
  static/images/hand_card.svg
  static/images/pencil-logo-original.svg
  static/images/pencil-logo.svg
  static/images/pencil.png
  static/js/main.js
  templates/base.html
  templates/index.html
Labels: FIX

#169 fix: main page rank 카드 세로로 바꾸기
  static/css/styles.css
  templates/main.html
Labels: FIX

#172 FIX: 카드 디테일 댓글
  card/templates/card/detail.html
  card/views.py
Labels: FIX

#174 DOCUMENT: 리드미 작성
  README.assets/crawling1.png
  README.assets/crawling2.png
  README.assets/crawling3.png
  README.assets/image-20221214165930377.png
  README.assets/mainpage1.png
  README.assets/mainpage2.png
  README.assets/profile.png
  README.assets/검색기능.png
  README.assets/고객문의.png
  README.assets/레이아웃3.png
  README.assets/맞춤카드.png
  README.assets/모델.png
  README.assets/카드디테일.png
  README.assets/카드비교.png
  README.assets/카드사페이지.png
  README.assets/카드이벤트.png
  README.assets/커뮤니티.png
  README.assets/프로젝트수행절차.png
  README.assets/화면_설계.png
  README.md
  card/views.py
  requirements.txt
  servicecenter/templates/servicecenter/detail.html
  servicecenter/views.py
Labels: documentation

#176 Toto
  card/templates/card/detail.html
  magazine/migrations/0003_auto_20221220_1808.py
  magazine/models.py
  magazine/templates/magazine/detail.html
  servicecenter/templates/servicecenter/detail.html
  servicecenter/urls.py
  servicecenter/views.py
  static/css/service_detail.css
Labels: enhancement, FEAT
