Repository nahkim/ClassCard, pull requests merged in 2022-11, with the labels that each got.

#1 TEST : 테스트
  test.txt
Labels: documentation

#2 FEAT : 개발 환경 설정 추가
  config/settings.py
  config/urls.py
  requirements.txt
  static/css/styles.css
  static/images/000007.JPG
  static/js/test.js
  templates/base.html
  test.txt
Labels: FEAT

#3 FEAT : NAV 구현
  static/css/styles.css
  static/images/header_bag.svg
  static/images/header_close.svg
  static/images/header_search copy.svg
  static/images/header_search.svg
  static/js/test.js
  templates/base.html
Labels: FEAT

#4 Rothy
  config/settings.py
  config/urls.py
Labels: FEAT

#5 STYLE : 앱 추가
  accounts/__init__.py
  accounts/admin.py
  accounts/apps.py
  accounts/migrations/__init__.py
  accounts/models.py
  accounts/tests.py
  accounts/urls.py
  accounts/views.py
  articles/__init__.py
  articles/admin.py
  articles/apps.py
  articles/migrations/__init__.py
  articles/models.py
  articles/tests.py
  articles/urls.py
  articles/views.py
  card/__init__.py
  card/admin.py
  card/apps.py
  card/migrations/__init__.py
  card/models.py
  card/tests.py
  card/urls.py
  card/views.py
  config/settings.py
  config/urls.py
  config/views.py
  magazine/__init__.py
  magazine/admin.py
  magazine/apps.py
  magazine/migrations/__init__.py
  magazine/models.py
  magazine/tests.py
  magazine/urls.py
  magazine/views.py
  templates/main.html
Labels: STYLE

#6 FEAT: NAV 코드 수정 및 구현
  templates/base.html
Labels: FEAT

#8 FEAT: NAV 기능추가
  config/settings.py
  templates/base.html
  templates/main.html
Labels: FEAT

#10 STYLE : 패키지 추가 및 구글 로그인 등록
  config/settings.py
  requirements.txt
  soso/templates/soso/login.html
Labels: STYLE, CHORE

#11 FEAT: NAV 색상 및 메뉴 변경
  static/css/styles.css
  static/images/class-card-img2.png
  static/images/class-card-img4.png
  static/images/class-card-img5.png
  static/images/class-card-img6.png
  static/images/class-card-img7.png
  static/images/class-card-img8.png
  static/images/class-logo.png
  static/images/header_apple.svg
  static/images/header_search copy.svg
  templates/base.html
Labels: FEAT

#12 FIX : 소셜 로그인 기능 수정 (google)
  config/settings.py
  soso/templates/soso/login.html
Labels: FIX

#13 Ready
  templates/main.html
Labels: FEAT

#15 FEAT : magazine 모델 및 기본 기능 작성
  config/settings.py
  config/urls.py
  magazine/forms.py
  magazine/migrations/0001_initial.py
  magazine/migrations/0002_rename_magezine_magazine.py
  magazine/migrations/0003_comment.py
  magazine/migrations/0004_alter_comment_parent_comment.py
  magazine/migrations/0005_auto_20221130_1720.py
  magazine/models.py
  magazine/templates/magazine/create.html
  magazine/templates/magazine/detail.html
  magazine/templates/magazine/index.html
  magazine/urls.py
  magazine/views.py
Labels: FEAT
